CREATE DATABASE UNIVERSIDAD;
USE UNIVERSIDAD;

CREATE TABLE CARRERA(
CODIGO_CARRERA VARCHAR(5) PRIMARY KEY,
NOMBRE_CARRERA VARCHAR(20) NOT NULL
)  ENGINE=INNODB;

CREATE TABLE CATEDRATICO(
CODIGO_CATEDRATICO VARCHAR(5) PRIMARY KEY,
NOMBRE_CATEDRATICO VARCHAR(50) NOT NULL,
CUI_CATEDRATICO VARCHAR(20) NOT NULL,
ESTATUS_CATEDRATICO VARCHAR(1) NOT NULL,
FOREIGN KEY (CODIGO_CARRERA) REFERENCES CARRERA(CODIGO_CARRERA)
)  ENGINE=INNODB;

CREATE TABLE ESTUDIANTE(
CODIGO_ESTUDIANTE VARCHAR(5) PRIMARY KEY,
NOMBRE_ESTUDIANTE VARCHAR(50) NOT NULL,
CUI_ESTUDIANTE VARCHAR(20) NOT NULL,
ESTATUS_CATEDRATICO VARCHAR(1) NOT NULL,
FOREIGN KEY (CODIGO_CARRERA) REFERENCES CARRERA(CODIGO_CARRERA)
)  ENGINE=INNODB;